name: jsdoc
on:
 push:
   

jobs:
  generate-jsdoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm i -D jsdoc
      - run: npm run doc
